# Generated by Django 4.2.4 on 2024-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('equipment', models.CharField(max_length=90)),
                ('video', models.URLField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
